### ISSUE TITLE
Bot is not deleted in TS3Audiobot

### ISSUE THREAD

**Issue by CookieCr2nk** [SMNJAN/smn-single#3]
When i delete a bot over the webinterface, the bot isn't removed on TS3Audiobot. My solution is to make a API request to delete the bot.
```Requested: /api/settings/delete/<Botname>```

**Comment by Kuhva** [comment]
Will be applied with the next update

**Comment by MikkelDK** [comment]
@Kuhva When will it be applied for the next update?
