### ISSUE TITLE
Webinterface mit TS3AudioBot verbinden

### ISSUE THREAD

**Issue by SorryDudeGotcha** [SMNJAN/smn-single#5]
Hallo,
ich brauche Hilfe den Bot mit dem Webinterface zu verbinden. 

Ich habe alles korrekt eingetragen bekomme jedoch diesen Error von Apache2:
`[Wed Apr 01 19:38:35.666239 2020] [:error] [pid 10159] [client <meineip>] PHP Parse error:  syntax error, unexpected 'use' (T_USE), expecting identifier (T_STRING) in /var/www/html/cp/vendor/smnjan/ts3ab/Ts3CommandCaller.php on line 149, referer: https://<ip>/bots.php`

Meine Web-Konfiguration beim TS3AudioBot sieht wie folgt aus:
`[web]
#An array of all urls the web api should be possible to be accessed with.
hosts = ["localhost", "127.0.0.1"]
#The port for the web server.
port = 58913

[web.api]
#If you want to enable the web api.
enabled = true
#Limits the maximum command complexity to prevent endless loops.
command_complexity = 64
#See: bot.commands.matcher
matcher = "exact"

[web.interface]
#If you want to enable the webinterface.
enabled = false
#The webinterface folder to host. Leave empty to let the bot look for default locations.
path = ""`

Und meine Einträge in der Config.php so:
`<?php
/**
 * Created by Kuhva.
 */
namespace smnjan;

class Config
{
    const
        DB_HOST = "localhost",
        DB_NAME = "<user>",
        DB_USER = "<dbname>",
        DB_PSSWD = "<pw>"; 
      

    const nodes = array(
        1 => array(
            'host' => '<ip des servers>',
            'port' => 58913,
            'key'  => 'id:key',
            'name' => 'Test'
        )
    );
}`
Die Connection zu MySQL funktioniert, da ich mich anmelden kann, wenn ich aber einen Bot erstellen will bleibt der "Erstellen"-Button gedrückt und es passiert nichts.

Hoffe jemand kann mir auch noch 5 Monate nach Release helfen :)

MfG

**Comment by Kuhva** [comment]
Welche PHP Version nutzt du ?
